version: '3.7'
services:
  eks-node-rollout:
    image: mx51io/eks-node-rollout:latest
    build: .
    volumes:
      - .:/work
    working_dir: /work

  pep8:
    image: eeacms/pep8
    entrypoint: []
    volumes:
      - .:/code:Z
    network_mode: "none"
    working_dir: /code
